#!/usr/bin/python2.7
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

limit = 4000000
sum = 0
x = 0
y = 1

while True:
    z = x + y
    x, y = y, z
    if z <= limit:
        if not z % 2:
            sum += z
    else:
        break

print sum
